### PR TITLE
Add FR folders

### PR DESCRIPTION
**Pull request by Fr-Dae**
https://github.com/Cediner/ArdClient/issues/86
- add FR translation
- Add modification of ZH button by @zongxiaotao

### CODE REVIEW

**Comment by Fr-Dae** [comment]
why do you use properties file and not json like 
as the rest of the world does?
it's a lot harder to manipulate and translate :/ 

if you ever decide to follow the standard and use json, the files are already available in json FR

**Comment by Cediner** [comment]
I don't use localization
this has been done since the amber client
your correction is not complete
but I added
https://github.com/Cediner/ArdClient/commit/6e8f7e87f7e08784e7e9e3c871febc08e7c8ce34

**Comment by Fr-Dae** [comment]
hello, what do you mean by "it's not complete"?

and why did you close it rather than merge it?

**Comment by Fr-Dae** [comment]
Why are you adding my work without crediting me as a contributor?

**Pull request closed without merging**
