### PR TITLE
add conteiner sort in PBot

### PR DESCRIPTION
**Pull request by khris190**
python scripts dont work for me so i added 2 sorting scripts written in PBot

### CODE REVIEW

**Comment by Cediner** [comment]
And what do you want?
Inventory sorting has exist on alt+rmc on inventory window.
You can also use your scripts yourself without adding them to Github.
Python is complex and requires understanding to get them running.

**Comment by khris190** [comment]
i didn't know cause it doesn't work with default linux behaviour on a few distros alt+rightclick resizes windows so it doesnt show that menu

**Comment by khris190** [comment]
i check that sort, You said about, its slow and breaks on bigger items

**Comment by Cediner** [comment]
Thanks I'll know about linux.
Yes, it needs improvement, but it takes time and an algorithm.

**Pull request closed without merging**
